// Code generated by github.com/pjoc-team/go-options.  DO NOT EDIT.

package examples

type ApplyOptionFunc func(c *eoptions) error

func (f ApplyOptionFunc) apply(c *eoptions) error {
	return f(c)
}

func newEoptions(options ...Option) (eoptions, error) {
	var c eoptions
	err := applyEoptionsOptions(&c, options...)
	return c, err
}

func applyEoptionsOptions(c *eoptions, options ...Option) error {
	for _, o := range options {
		if err := o.apply(c); err != nil {
			return err
		}
	}
	return nil
}

type Option interface {
	apply(*eoptions) error
}

func OptionName(o string) ApplyOptionFunc {
	return func(c *eoptions) error {
		c.Name = o
		return nil
	}
}
