// Code generated by github.com/pjoc-team/go-options.  DO NOT EDIT.

package examples

// ApplyEOptionFunc the func of eoptions
type ApplyEOptionFunc func(c *eoptions) error

func (f ApplyEOptionFunc) apply(c *eoptions) error {
	return f(c)
}

// NewEoptions create Eoptions with options
func NewEoptions(opts ...EOption) (eoptions, error) {
	var c eoptions
	err := applyEoptionsOptions(&c, opts...)
	return c, err
}

func newEoptions(opts ...EOption) (eoptions, error) {
	var c eoptions
	err := applyEoptionsOptions(&c, opts...)
	return c, err
}

func applyEoptionsOptions(c *eoptions, options ...EOption) error {
	for _, o := range options {
		if err := o.apply(c); err != nil {
			return err
		}
	}
	return nil
}

// EOption interface EOption
type EOption interface {
	apply(*eoptions) error
}

// WithName option func
func WithName(o string) ApplyEOptionFunc {
	return func(c *eoptions) error {
		c.Name = o
		return nil
	}
}

// WithFilterFunc option func
func WithFilterFunc(o FilterFunc) ApplyEOptionFunc {
	return func(c *eoptions) error {
		c.FilterFunc = o
		return nil
	}
}
