// Code generated by github.com/pjoc-team/go-options.  DO NOT EDIT.

package examples

// ApplyWithFunc the func of eoptions
type ApplyWithFunc func(c *eoptions) error

func (f ApplyWithFunc) apply(c *eoptions) error {
	return f(c)
}

func newEoptions(options ...With) (eoptions, error) {
	var c eoptions
	err := applyEoptionsOptions(&c, options...)
	return c, err
}

func applyEoptionsOptions(c *eoptions, options ...With) error {
	for _, o := range options {
		if err := o.apply(c); err != nil {
			return err
		}
	}
	return nil
}

// With interface With
type With interface {
	apply(*eoptions) error
}

// WithName option func
func WithName(o string) ApplyWithFunc {
	return func(c *eoptions) error {
		c.Name = o
		return nil
	}
}
